"""add_lunch_history_table

Revision ID: 1991e2f3d3bc
Revises: 995ad0e072c8
Create Date: 2026-04-20 08:19:45.681275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1991e2f3d3bc'
down_revision: Union[str, Sequence[str], None] = '995ad0e072c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lunch_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('attendees', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lunch_history_date', 'lunch_history', ['date'], unique=False)
    op.create_index('ix_lunch_history_restaurant_id', 'lunch_history', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lunch_history_restaurant_id', table_name='lunch_history')
    op.drop_index('ix_lunch_history_date', table_name='lunch_history')
    op.drop_table('lunch_history')
    # ### end Alembic commands ###
