"""add_user_blacklist_table

Revision ID: 855e8189a896
Revises: 1991e2f3d3bc
Create Date: 2026-04-20 08:35:34.242824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '855e8189a896'
down_revision: Union[str, Sequence[str], None] = '1991e2f3d3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_blacklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'restaurant_id', name='uq_user_restaurant')
    )
    op.create_index('ix_user_blacklist_expires_at', 'user_blacklist', ['expires_at'], unique=False)
    op.create_index('ix_user_blacklist_user_id', 'user_blacklist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_blacklist_user_id', table_name='user_blacklist')
    op.drop_index('ix_user_blacklist_expires_at', table_name='user_blacklist')
    op.drop_table('user_blacklist')
    # ### end Alembic commands ###
