"""add users and restaurants tables

Revision ID: 995ad0e072c8
Revises: 
Create Date: 2026-04-20 07:41:21.782790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '995ad0e072c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('vicinity', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('photo_reference', sa.Text(), nullable=True),
    sa.Column('closed_weekdays', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('closed_monthly_ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id')
    )
    op.create_index('ix_restaurants_added_by', 'restaurants', ['added_by'], unique=False)
    op.create_index('ix_restaurants_place_id', 'restaurants', ['place_id'], unique=False)
    op.create_index('ix_restaurants_source', 'restaurants', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_restaurants_source', table_name='restaurants')
    op.drop_index('ix_restaurants_place_id', table_name='restaurants')
    op.drop_index('ix_restaurants_added_by', table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_table('users')
    # ### end Alembic commands ###
